### ISSUE TITLE
iOS [Fabric] Value of Info.plist key "Fabric" must be a NSDictionary when using Firebase instead of Fabric

### ISSUE THREAD

**Issue by campioncino** [kiwi-bop/flutter_crashlytics#27]
I'm using the plugin via Firebase, without declare the fabric API Key. On iOS I've got this error when invoke 
`await FlutterCrashlytics().initialize();`
Works great on Android.

**Comment by jaumard** [comment]
I'm can't help you much with Firebase usage as I don't use it :/ is it working if you specify it ?

**Comment by flaviosuardi** [comment]
@campioncino I solved this issue. The problem is this flutter plugin doesn't include firebase core. So you have include it in your project and inizialize it:
1. Import `firebase_core` 0.2.5+1 in flutter project, you can find it here: https://pub.dartlang.org/packages/firebase_core
2. In iOS project, open `AppDelegate` and inizialize `Firebase` following this guide https://firebase.google.com/docs/ios/setup in particular do the stuff described `Initialize Firebase in your app` chapter only.

I suggest to @jaumard to include this procedure in README.md so maybe someone else who use Firebase Crashlytics like us could benefit.

**Comment by jaumard** [comment]
@flaviosuardi if you're able to make a PR about it I'll gladly merge it :) 

@campioncino `.h` are just definition and `.m` implementation, so put it on the `.m`
