### ISSUE TITLE
Readme update for Firebase Crashlytics?

### ISSUE THREAD

**Issue by holyspidoo** [kiwi-bop/flutter_crashlytics#9]
Love this plugin so much!!

Maybe the readme could be updated for using Firebase Crashlytics? When doing so, the API keys parts are not needed. Everything else is the same and works great.

**Comment by jaumard** [comment]
Thanks for the feedback ! Never used Firebase Crashlytics yet :) also this plugin embed Fabric binaries for Crashlytics and not Firebase one (doesn't know if it matters or not ^^) 
How firebase know which project it is if you don't have any API key or setup somewhere ? 

If you want to put some sentences about setup with Firebase Crashlytics on the readme don't hesitate to make a PR with :) I'll gladly merge it

**Comment by holyspidoo** [comment]
Works great so far with Firebase. Basically, you need to run your app once and firebase crashlytics works. I followed your readme but did not add both parts about the API keys. Fabric moving to firebase next year.

**Comment by jaumard** [comment]
Ho ok :) I know that Fabric is moving totally to firebase next year, but for now this plugin is temporary since Google is supposed to publish one with real support for dart/flutter. So I'm waiting for them see what they will offer. Depending on that I'll migrate the plugin to Firebase :)

If it already work it's awesome ! :)

**Comment by jaumard** [comment]
Readme updated with your notes :) thanks again
